name: Deploy to Firebase functions on merge
 'on':
   push:
     branches:
       - main
 jobs:
   build_and_deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: cd functions && npm deploy
